export const authConstants = {
    GET_OTP_REQUEST : 'GET_OTP_REQUEST',
    GET_OTP_SUCCESS : 'GET_OTP_SUCCESS',
    GET_OTP_FAILURE : 'GET_OTP_FAILURE',
    VERIFY_OTP_REQUEST : 'VERIFY_OTP_REQUEST',
    VERIFY_OTP_SUCCESS : 'VERIFY_OTP_SUCCESS',
    VERIFY_OTP_FAILURE : 'VERIFY_OTP_FAILURE',
    REGISTER_REQUEST : 'REGISTER_REQUEST',
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    REGISTER_FAILURE : 'REGISTER_FAILURE',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE',
}

export const initialdata_constants = {
    GET_ALL_DATA_SUCCESS : "GET_ALL_DATA_SUCCESS",
}

export const cartConstants = {
    ADD_TO_CART_SUCCESS : "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE : "ADD_TO_CART_FAILURE",
    ADD_TO_CART_REQUEST : "ADD_TO_CART_REQUEST",
    FETCH_CART_SUCCESS : "FETCH_CART_SUCCESS",
    FETCH_CART_FAILURE : "FETCH_CART_FAILURE",
    FETCH_CART_REQUEST : "FETCH_CART_REQUEST",
    DELETE_CART_SUCCESS : "DELETE_CART_SUCCESS",
    DELETE_CART_FAILURE : "DELETE_CART_FAILURE",
    DELETE_CART_REQUEST : "DELETE_CART_REQUEST",

}

export const searchConstants = {
    ADD_SEARCH_ARRAY : "ADD_SEARCH_ARRAY"
}

export const orderConstants = {
    ORDER_SUCCESS: "ORDER_SUCCESS",
    PAYMENT_SUCCESS: "PAYMENT_SUCCESS"
}